### ISSUE TITLE
More friendly `homely add`

### ISSUE THREAD

**Issue by phodge** [phodge/homely#19]
Work or at least die with a helpful error message when:

* Target dir is not a git repo
* Target dir doesn't have a HOMELY.py script - when we add a repo that doesn't have a HOMELY.py script we should raise an error and provide instructions on how to write a HOMELY.py script (and not try to do the ``homely update``).
* Target dir doesn't have any commits
* Target dir doesn't have a remote

**Comment by phodge** [comment]
Traceback when target dir isn't a repo:

```
[nigel@vegas ~]$ homely add dotfiles
[Sat Feb 18 10:56:24 2017]     /home/nigel/dotfiles$ git rev-list --max-parents=0 HEAD
[Sat Feb 18 10:56:24 2017]     2> fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
[Sat Feb 18 10:56:24 2017]     2> Use '--' to separate paths from revisions, like this:
[Sat Feb 18 10:56:24 2017]     2> 'git <command> [<revision>...] -- [<file>...]'
[Sat Feb 18 10:56:24 2017] ERR   Unexpected exit code 128. Expected 0
Traceback (most recent call last):
  File "/home/nigel/.local/bin/homely", line 3, in <module>
    main()
  File "/home/nigel/.local/lib/python3.4/site-packages/homely/_scripts/homely.py", line 331, in main
    homely()
  File "/home/nigel/.local/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/nigel/.local/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/nigel/.local/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nigel/.local/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nigel/.local/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/nigel/.local/lib/python3.4/site-packages/homely/_scripts/homely.py", line 37, in proxy
    command(**kwargs)
  File "/home/nigel/.local/lib/python3.4/site-packages/homely/_scripts/homely.py", line 98, in add
    repo.getrepoid(),
  File "/home/nigel/.local/lib/python3.4/site-packages/homely/_vcs/git.py", line 65, in getrepoid
    stdout = system(cmd, cwd=self.repo_path, stdout=True)[1]
  File "/home/nigel/.local/lib/python3.4/site-packages/homely/_ui.py", line 511, in system
    raise SystemError(message)
SystemError: Unexpected exit code 128. Expected 0
```

**Comment by phodge** [comment]
Completed in 0.11.9
